services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Entity\OptInDomain\OptInDomainRepository:
  App\Domain\Entity\OptOutDomain\OptOutDomainRepository:

  App\Domain\OptInDomain\Request\OptInDomainParamConverter:
    tags:
      - { name: request.param_converter, converter: app.optInDomain }

  App\Domain\OptOutDomain\Request\OptOutDomainParamConverter:
    tags:
      - { name: request.param_converter, converter: app.optOutDomain }

  App\Domain\OptInDomain\Security\OptInDomainVoter:
  App\Domain\OptOutDomain\Security\OptOutDomainVoter:
