services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Entity\OptIn\OptInDomain\OptInDomainRepository:
  App\Domain\Entity\OptOut\OptOutDomain\OptOutDomainRepository:
  App\Domain\Entity\OptIn\OptInEmail\OptInEmailRepository:
  App\Domain\Entity\OptOut\OptOutEmail\OptOutEmailRepository:

  App\Domain\OptIn\OptInDomain\Validator\UniqueDomainValidator:
  App\Domain\OptOut\OptOutDomain\Validator\UniqueDomainValidator:
  App\Domain\OptOut\OptOutEmail\Validator\UniqueEmailValidator:
  App\Domain\OptIn\OptInEmail\Validator\UniqueEmailValidator:

  App\Domain\OptIn\OptInDomain\Security\OptInDomainVoter:
  App\Domain\OptOut\OptOutDomain\Security\OptOutDomainVoter:
  App\Domain\OptIn\OptInEmail\Security\OptInEmailVoter:
  App\Domain\OptOut\OptOutEmail\Security\OptOutEmailVoter:
