services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Entity\OptInDomain\OptInDomainRepository:

  command_handlers:
    namespace: App\Domain\User\Command\
    resource: '%kernel.project_dir%/src/Domain/User/Command/*Handler.php'
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  event_subscribers:
    namespace: App\Domain\User\Command\
    resource: '%kernel.project_dir%/src/Domain/User/Command/*Subscriber.php'
    tags:
      - { name: messenger.message_handler, bus: event.bus }