services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Entity\OptInDomain\OptInDomainRepository:

  App\Domain\OptInDomain\Request\OptInDomainParamConverter:
    tags:
      - { name: request.param_converter, converter: app.optInDomain }

  App\Domain\OptInDomain\Security\OptInDomainVoter:
