services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Domain\Entity\UserAlias\UserAliasRepository:

  command_handlers:
    namespace: App\Domain\UserAlias\Command\
    resource: '%kernel.project_dir%/src/Domain/UserAlias/Command/*Handler.php'
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  event_subscribers:
    namespace: App\Domain\UserAlias\Command\
    resource: '%kernel.project_dir%/src/Domain/UserAlias/Command/*Subscriber.php'
    tags:
      - { name: messenger.message_handler, bus: event.bus }

  App\Domain\UserAlias\Request\UserAliasParamConverter:
    tags:
      - { name: request.param_converter, converter: app.alias }

  App\Domain\UserAlias\Security\UserAliasVoter:
  App\Domain\UserAlias\Validator\UniqueEntryValidator: